[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
  "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
  "forge-std/=lib/forge-std/src/"
]
ffi = true
gas_reports = ["MyToken", "MyTokenTest"]

# Add this section for Hedera testnet
[rpc_endpoints]
mainnet = "${HEDERA_RPC_URL}"

[profile.default.fuzz]
runs = 10
max_test_rejects = 65536

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
